[package]
name = "bb_cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "bb"
path = "src/main.rs"

[dependencies]
anyhow = "1"
bb_core = { path = "../bb_core" }
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
